# Generated by Django 5.0.2 on 2024-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='dni',
            field=models.IntegerField(default='0002'),
            preserve_default=False,
        ),
    ]
